language: node_js
node_js:
  - 12

script: npm run build:prod -- --base-href "/qualidade-agua/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist/qualidade-agua
  target_branch: pages
  on:
    branch: master
